export enum EventType {
    userJailed = 0,
    userHospitalized = 1,
    userSpooked = 3,
    juryDuty = 4,
    foxCopDisabled = 5,
    foxLawyerDisabled = 6,
    excitedBearDisabled = 7,
    userOnTrial = 8,
    userOnHunt = 9,
    transactionConfirmation = 10,
    userWalletSnapshotRequest = 12,
    deceptivelyCuteGatorDisabled = 13,
    userPhantomFoxed = 14,
    userInsane = 15,
    userLaidTrapInChannel = 16,
}
